# Generated by Django 4.0.5 on 2022-06-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=16)),
                ('gender', models.CharField(max_length=16)),
                ('dob', models.CharField(max_length=16)),
                ('profile', models.URLField(null=True)),
                ('description', models.CharField(max_length=128, null=True)),
                ('facebook', models.CharField(max_length=128, null=True)),
                ('insta', models.CharField(max_length=128, null=True)),
                ('twitter', models.CharField(max_length=128, null=True)),
                ('linkedin', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_lat', models.FloatField(null=True)),
                ('last_lon', models.FloatField(null=True)),
                ('intersts', models.ManyToManyField(to='user.interest')),
            ],
        ),
        migrations.AddField(
            model_name='interest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.interestcategory'),
        ),
    ]
